#!/bin/bash
set -e

if [[ "$(uname -s)" == Darwin ]]; then
	function set_vars {
		export DYLD_INSERT_LIBRARIES="$PWD/goal.dylib"
		export DYLD_FORCE_FLAT_NAMESPACE=1
	}
else
	function set_vars {
		export LD_PRELOAD="$PWD/goal.so"
	}
fi

set_vars
exec "$@"
